# Name       : Tikva
# Version    : 0.4.0
# Released   : 2023-02-16

name = "Tikva"
license = "MIT"
licenselink = "https://github.com/geschke/hugo-tikva/blob/master/LICENSE.md"
description = "Tikva is a minimalistic Hugo theme, based on Bootstrap 4 framework"
homepage = "https://github.com/geschke/hugo-tikva/"
tags = ["theme", "core", "modern", "responsive", "bootstrap", "minimal", "blog", "font awesome", "white", "dark", "light" ]
features = ["responsive","blog"]
min_version = "0.100.0"

[author]
  name = "Ralf Geschke"
  homepage = "https://www.kuerbis.org"

# If porting an existing theme
[original]
  name = "Tikva theme for Grav CMS"
  homepage = "https://www.kuerbis.org/tikva-theme-for-grav-cms/"
  repo = "https://github.com/geschke/grav-theme-tikva"
